version: '3.0'

networks:
  nw:
    driver: bridge
services:
  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - nw
    depends_on:
      - wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wp-php
    networks:
      - nw
    depends_on:
      - mariadb
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - nw
# volumes:
#   DB:
#   WP:
