FROM debian:buster

RUN apt-get update && apt-get install -y \
	php7.3-fpm \
	php7.3-mysql \
	wget \
	curl

WORKDIR /

COPY conf tmp

COPY tools tools

RUN mkdir -p /var/www/html

RUN mv /tmp/www.conf /etc/php/7.3/fpm/pool.d/www.conf

RUN wget https://wordpress.org/latest.tar.gz && \
	tar -xvf latest.tar.gz && \
	mv wordpress/* /var/www/html/ && \
	rm -rf wordpress && \
	rm -r latest.tar.gz && \
	mv /tmp/wp-config.php /var/www/html/wp-config.php && \
	chown -R www-data:www-data /var/www/html/* && \
	chmod -R 777 /var/www/html/* && \
	rm /var/www/html/wp-config-sample.php
# RUN sh /tools/init.sh


	# && \
	# mv tmp/php.ini /etc/php/7.3/fpm/php.ini
# ENTRYPOINT ["php7.3"]
# CMD 
ENTRYPOINT ["sh","/tools/entrypoint.sh"]
#ENTRYPOINT ["sh","/tools/entrypoint.sh"]//php-fpm7.3 -F

