FROM debian:buster

RUN apt-get update && apt-get install -y \
	mariadb-server \
	php-mbstring

WORKDIR /

COPY conf tmp

COPY tools tools

RUN service mysql start &&\
	service mysql stop

ENTRYPOINT ["sh","/tools/entrypoint.sh"]
