FROM debian:buster

RUN apt-get update && apt-get install -y\
	nginx \
	openssl

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/localhost.dev.key -out /etc/ssl/certs/localhost.dev.crt -subj '/C=KR'

WORKDIR /

COPY conf tmp

COPY tools tools

RUN mv tmp/default /etc/nginx/sites-available/default && \
	echo "daemon off;" >> /etc/nginx/nginx.conf

EXPOSE 443

ENTRYPOINT ["nginx"]
